FROM alpine:latest

# Install python, pip and libs 
RUN apk add --update python \
    ca-certificates \
    py-pip \
    python-dev \
    bash \
    libffi-dev \
    libressl-dev \
    cyrus-sasl-dev \
    musl-dev \
    gcc \
    g++ \
    mariadb-dev \
    postgresql-dev

# Copy requirements to work dir
WORKDIR /var/www/bit

ADD /incubator-superset/setup.py /var/www/bit/incubator-superset/
ADD /incubator-superset/superset/assets/package.json /var/www/bit/incubator-superset/superset/assets/package.json
ADD /incubator-superset/superset/bin/superset /var/www/bit/incubator-superset/superset/bin/superset


ADD requirements.txt /var/www/bit
ADD /connectors/requirements.txt /var/www/bit/connectors/
ADD /connectors/appsflyer/requirements.txt /var/www/bit/connectors/appsflyer/
ADD /connectors/db_sql/requirements.txt /var/www/bit/connectors/db_sql/
ADD /connectors/fb_ads/requirements.txt /var/www/bit/connectors/fb_ads/
ADD /connectors/google_adwords/requirements.txt /var/www/bit/connectors/google_adwords/

# Install dependencies
RUN pip install -r /var/www/bit/requirements.txt
