from .gender import GenderPerformanceReportAdapter
from .campaign import CampaignPerformanceReportAdapter
from .geo import GeoPerformanceReportAdapter
from .placement import PlacementPerformanceReportAdapter
from .search_query import SearchQueryPerformanceReportAdapter
from .placeholder import PlaceHolderPerformanceReportAdapter
