"""empty message

Revision ID: 05a179c2c758
Revises: c90e78bc3ef9
Create Date: 2017-08-18 18:08:42.984000

"""

# revision identifiers, used by Alembic.
revision = '05a179c2c758'
down_revision = 'c90e78bc3ef9'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_adwords_connector',
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['bit_connectors.id'], ),
    sa.PrimaryKeyConstraint('connector_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bit_adwords_connector')
    # ### end Alembic commands ###
