"""empty message

Revision ID: 2b6faa1ecf87
Revises: 15e82138e107
Create Date: 2017-08-08 14:36:13.418000

"""

# revision identifiers, used by Alembic.
revision = '2b6faa1ecf87'
down_revision = '15e82138e107'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_etl_tables', sa.Column('is_scheduled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_etl_tables', 'is_scheduled')
    # ### end Alembic commands ###
