"""empty message

Revision ID: 2c2184acc7bd
Revises: e86a4e731a84
Create Date: 2018-02-02 10:18:27.988000

"""

# revision identifiers, used by Alembic.
revision = '2c2184acc7bd'
down_revision = 'e86a4e731a84'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_facebook_ad_account', sa.Column('from_date', sa.String(length=255), nullable=True))
    op.add_column('bit_facebook_ad_account', sa.Column('to_date', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_facebook_ad_account', 'to_date')
    op.drop_column('bit_facebook_ad_account', 'from_date')
    # ### end Alembic commands ###
