"""empty message

Revision ID: 360caaea22f0
Revises: feb789fcbf9e
Create Date: 2017-08-23 15:53:49.011000

"""

# revision identifiers, used by Alembic.
revision = '360caaea22f0'
down_revision = 'feb789fcbf9e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_appsflyer_connector',
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=True),
    sa.Column('url_pat', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['bit_connectors.id'], ),
    sa.PrimaryKeyConstraint('connector_id')
    )
    op.drop_table('bit_connectors_appsflyer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_connectors_appsflyer',
    sa.Column('app_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('api_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url_pat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connector_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], [u'bit_connectors.id'], name=u'bit_connectors_appsflyer_connector_id_fkey')
    )
    op.drop_table('bit_appsflyer_connector')
    # ### end Alembic commands ###
