"""empty message

Revision ID: 3c663dc9e90b
Revises: 05a179c2c758
Create Date: 2017-08-21 13:22:29.248000

"""

# revision identifiers, used by Alembic.
revision = '3c663dc9e90b'
down_revision = '05a179c2c758'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_performance_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('campaign_source', sa.String(length=250), nullable=True),
    sa.Column('campaign_name', sa.String(length=250), nullable=True),
    sa.Column('campaign_id', sa.String(length=250), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('clicks_unique', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=17, scale=5), nullable=True),
    sa.Column('breakdowns', postgresql.HSTORE(text_type=sa.Text()), nullable=True),
    sa.Column('measurements', postgresql.HSTORE(text_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bit_performance_report_breakdowns'), 'bit_performance_report', ['breakdowns'], unique=False)
    op.create_index(op.f('ix_bit_performance_report_campaign_id'), 'bit_performance_report', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_bit_performance_report_campaign_name'), 'bit_performance_report', ['campaign_name'], unique=False)
    op.create_index(op.f('ix_bit_performance_report_campaign_source'), 'bit_performance_report', ['campaign_source'], unique=False)
    op.create_index(op.f('ix_bit_performance_report_date'), 'bit_performance_report', ['date'], unique=False)
    op.create_index(op.f('ix_bit_performance_report_day'), 'bit_performance_report', ['day'], unique=False)
    op.create_index(op.f('ix_bit_performance_report_month'), 'bit_performance_report', ['month'], unique=False)
    op.create_index(op.f('ix_bit_performance_report_name'), 'bit_performance_report', ['name'], unique=False)
    op.create_index(op.f('ix_bit_performance_report_year'), 'bit_performance_report', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bit_performance_report_year'), table_name='bit_performance_report')
    op.drop_index(op.f('ix_bit_performance_report_name'), table_name='bit_performance_report')
    op.drop_index(op.f('ix_bit_performance_report_month'), table_name='bit_performance_report')
    op.drop_index(op.f('ix_bit_performance_report_day'), table_name='bit_performance_report')
    op.drop_index(op.f('ix_bit_performance_report_date'), table_name='bit_performance_report')
    op.drop_index(op.f('ix_bit_performance_report_campaign_source'), table_name='bit_performance_report')
    op.drop_index(op.f('ix_bit_performance_report_campaign_name'), table_name='bit_performance_report')
    op.drop_index(op.f('ix_bit_performance_report_campaign_id'), table_name='bit_performance_report')
    op.drop_index(op.f('ix_bit_performance_report_breakdowns'), table_name='bit_performance_report')
    op.drop_table('bit_performance_report')
    # ### end Alembic commands ###
