"""empty message

Revision ID: 46799507436e
Revises: 6f122553e6e3
Create Date: 2017-08-08 16:20:23.495000

"""

# revision identifiers, used by Alembic.
revision = '46799507436e'
down_revision = '6f122553e6e3'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_facebook_ad_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('native_id', sa.String(length=255), nullable=True),
    sa.Column('billing_event', sa.String(length=255), nullable=True),
    sa.Column('budget_remaining', sa.String(length=255), nullable=True),
    sa.Column('configured_status', sa.String(length=255), nullable=True),
    sa.Column('daily_budget', sa.String(length=255), nullable=True),
    sa.Column('effective_status', sa.String(length=255), nullable=True),
    sa.Column('lifetime_budget', sa.String(length=255), nullable=True),
    sa.Column('optimization_goal', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('bid_amount', sa.Integer(), nullable=True),
    sa.Column('frequency_cap', sa.Integer(), nullable=True),
    sa.Column('frequency_cap_reset_period', sa.Integer(), nullable=True),
    sa.Column('lifetime_frequency_cap', sa.Integer(), nullable=True),
    sa.Column('lifetime_imps', sa.Integer(), nullable=True),
    sa.Column('is_autobid', sa.Boolean(), nullable=True),
    sa.Column('is_average_price_pacing', sa.Boolean(), nullable=True),
    sa.Column('recurring_budget_semantics', sa.Boolean(), nullable=True),
    sa.Column('rtb_flag', sa.Boolean(), nullable=True),
    sa.Column('use_new_app_click', sa.Boolean(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bit_facebook_ad_sets_native_id'), 'bit_facebook_ad_sets', ['native_id'], unique=True)
    op.create_index(op.f('ix_bit_facebook_ad_sets_status'), 'bit_facebook_ad_sets', ['status'], unique=False)
    op.create_table('bit_facebook_connector',
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['bit_connectors.id'], ),
    sa.PrimaryKeyConstraint('connector_id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('bit_facebook_ad_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('native_id', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.Integer(), nullable=True),
    sa.Column('synchronize', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.Column('timezone_offset_hours_utc', sa.Numeric(), nullable=True),
    sa.Column('amount_spent', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['bit_facebook_connector.connector_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bit_facebook_ad_account_account_id'), 'bit_facebook_ad_account', ['account_id'], unique=True)
    op.create_index(op.f('ix_bit_facebook_ad_account_native_id'), 'bit_facebook_ad_account', ['native_id'], unique=True)
    op.create_table('bit_facebook_ad_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('native_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('configured_status', sa.String(length=255), nullable=True),
    sa.Column('effective_status', sa.String(length=255), nullable=True),
    sa.Column('objective', sa.String(length=255), nullable=True),
    sa.Column('spend_cap', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('buying_type', sa.String(length=255), nullable=True),
    sa.Column('budget_rebalance_flag', sa.Boolean(), nullable=True),
    sa.Column('can_use_spend_cap', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('stop_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bit_facebook_ad_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bit_facebook_ad_campaigns_native_id'), 'bit_facebook_ad_campaigns', ['native_id'], unique=True)
    op.create_index(op.f('ix_bit_facebook_ad_campaigns_status'), 'bit_facebook_ad_campaigns', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bit_facebook_ad_campaigns_status'), table_name='bit_facebook_ad_campaigns')
    op.drop_index(op.f('ix_bit_facebook_ad_campaigns_native_id'), table_name='bit_facebook_ad_campaigns')
    op.drop_table('bit_facebook_ad_campaigns')
    op.drop_index(op.f('ix_bit_facebook_ad_account_native_id'), table_name='bit_facebook_ad_account')
    op.drop_index(op.f('ix_bit_facebook_ad_account_account_id'), table_name='bit_facebook_ad_account')
    op.drop_table('bit_facebook_ad_account')
    op.drop_table('bit_facebook_connector')
    op.drop_index(op.f('ix_bit_facebook_ad_sets_status'), table_name='bit_facebook_ad_sets')
    op.drop_index(op.f('ix_bit_facebook_ad_sets_native_id'), table_name='bit_facebook_ad_sets')
    op.drop_table('bit_facebook_ad_sets')
    # ### end Alembic commands ###
