"""empty message

Revision ID: 476bd75c847c
Revises: d8897dfe0b16
Create Date: 2017-08-29 12:21:30.167000

"""

# revision identifiers, used by Alembic.
revision = '476bd75c847c'
down_revision = 'd8897dfe0b16'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_connectors', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_connectors', 'type')
    # ### end Alembic commands ###
