"""empty message

Revision ID: 4ddf8216f390
Revises: 88642b45beae
Create Date: 2017-08-21 16:42:47.162000

"""

# revision identifiers, used by Alembic.
revision = '4ddf8216f390'
down_revision = '88642b45beae'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_adwords_google_drive_storage', sa.Column('connector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bit_adwords_google_drive_storage', 'bit_adwords_connector', ['connector_id'], ['connector_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bit_adwords_google_drive_storage', type_='foreignkey')
    op.drop_column('bit_adwords_google_drive_storage', 'connector_id')
    # ### end Alembic commands ###
