"""empty message

Revision ID: 5f1b9bb1cf7f
Revises: 7b084e67d65d
Create Date: 2017-08-28 14:44:12.916000

"""

# revision identifiers, used by Alembic.
revision = '5f1b9bb1cf7f'
down_revision = '7b084e67d65d'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bit_chiter_connector', 'bit_connectors', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bit_chiter_connector', type_='foreignkey')
    # ### end Alembic commands ###
