"""empty message

Revision ID: 6c459f0bd819
Revises: 958e493ca62f
Create Date: 2017-10-24 14:08:21.509000

"""

# revision identifiers, used by Alembic.
revision = '6c459f0bd819'
down_revision = '958e493ca62f'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_layer',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_dttm', sa.DateTime(), nullable=True),
    sa.Column('end_dttm', sa.DateTime(), nullable=True),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('short_descr', sa.String(length=500), nullable=True),
    sa.Column('long_descr', sa.Text(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['layer_id'], [u'annotation_layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ti_dag_state', 'annotation', ['layer_id', 'start_dttm', 'end_dttm'], unique=False)
    op.add_column(u'bit_adwords_campaign_performance_report', sa.Column('campaign_id', sa.String(length=255), nullable=True))
    op.add_column(u'dbs', sa.Column('impersonate_user', sa.Boolean(), nullable=True))
    op.add_column(u'sql_metrics', sa.Column('warning_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'sql_metrics', 'warning_text')
    op.drop_column(u'dbs', 'impersonate_user')
    op.drop_column(u'bit_adwords_campaign_performance_report', 'campaign_id')
    op.drop_index('ti_dag_state', table_name='annotation')
    op.drop_table('annotation')
    op.drop_table('annotation_layer')
    # ### end Alembic commands ###
