"""empty message

Revision ID: 6f122553e6e3
Revises: 2b6faa1ecf87
Create Date: 2017-08-08 15:21:30.370000

"""

# revision identifiers, used by Alembic.
revision = '6f122553e6e3'
down_revision = '2b6faa1ecf87'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bit_connectors')
    # ### end Alembic commands ###
