"""empty message

Revision ID: 79b791909dc3
Revises: 538751338a0f
Create Date: 2017-08-07 15:04:33.391000

"""

# revision identifiers, used by Alembic.
revision = '79b791909dc3'
down_revision = '538751338a0f'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_etl_tables', sa.Column('sync_periodic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_etl_tables', 'sync_periodic')
    # ### end Alembic commands ###
