"""empty message

Revision ID: 79d8578108f1
Revises: 186b9f3f06f4
Create Date: 2017-08-22 14:05:08.124000

"""

# revision identifiers, used by Alembic.
revision = '79d8578108f1'
down_revision = '186b9f3f06f4'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_adwords_campaign_performance_report', sa.Column('cost_per_mobile_app_installs', sa.Numeric(), nullable=True))
    op.add_column('bit_adwords_campaign_performance_report', sa.Column('cost_per_mobile_app_purchases', sa.Numeric(), nullable=True))
    op.add_column('bit_adwords_campaign_performance_report', sa.Column('mobile_app_installs', sa.Integer(), nullable=True))
    op.add_column('bit_adwords_campaign_performance_report', sa.Column('mobile_app_purchases', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_adwords_campaign_performance_report', 'mobile_app_purchases')
    op.drop_column('bit_adwords_campaign_performance_report', 'mobile_app_installs')
    op.drop_column('bit_adwords_campaign_performance_report', 'cost_per_mobile_app_purchases')
    op.drop_column('bit_adwords_campaign_performance_report', 'cost_per_mobile_app_installs')
    # ### end Alembic commands ###
