"""empty message

Revision ID: 7aacb302ef70
Revises: 476bd75c847c
Create Date: 2017-08-29 12:51:43.359000

"""

# revision identifiers, used by Alembic.
revision = '7aacb302ef70'
down_revision = '476bd75c847c'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_appsflyer_connector', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint(u'bit_appsflyer_connector_connector_id_fkey', 'bit_appsflyer_connector', type_='foreignkey')
    op.create_foreign_key(None, 'bit_appsflyer_connector', 'bit_connectors', ['id'], ['id'])
    op.drop_column('bit_appsflyer_connector', 'connector_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_appsflyer_connector', sa.Column('connector_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bit_appsflyer_connector', type_='foreignkey')
    op.create_foreign_key(u'bit_appsflyer_connector_connector_id_fkey', 'bit_appsflyer_connector', 'bit_connectors', ['connector_id'], ['id'])
    op.drop_column('bit_appsflyer_connector', 'id')
    # ### end Alembic commands ###
