"""empty message

Revision ID: 84ad5a52b596
Revises: 4ddf8216f390
Create Date: 2017-08-21 18:01:30.679000

"""

# revision identifiers, used by Alembic.
revision = '84ad5a52b596'
down_revision = '4ddf8216f390'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_data_source_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sync_time', sa.String(length=255), nullable=True),
    sa.Column('last_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bit_data_source_info_last_id'), 'bit_data_source_info', ['last_id'], unique=False)
    op.create_index(op.f('ix_bit_data_source_info_name'), 'bit_data_source_info', ['name'], unique=False)
    op.create_index(op.f('ix_bit_data_source_info_source'), 'bit_data_source_info', ['source'], unique=False)
    op.create_index(op.f('ix_bit_data_source_info_sync_time'), 'bit_data_source_info', ['sync_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bit_data_source_info_sync_time'), table_name='bit_data_source_info')
    op.drop_index(op.f('ix_bit_data_source_info_source'), table_name='bit_data_source_info')
    op.drop_index(op.f('ix_bit_data_source_info_name'), table_name='bit_data_source_info')
    op.drop_index(op.f('ix_bit_data_source_info_last_id'), table_name='bit_data_source_info')
    op.drop_table('bit_data_source_info')
    # ### end Alembic commands ###
