"""empty message

Revision ID: 87d7cfb1f7c0
Revises: 7dd23472cc3d
Create Date: 2017-12-10 20:53:28.798000

"""

# revision identifiers, used by Alembic.
revision = '87d7cfb1f7c0'
down_revision = '7dd23472cc3d'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_etl_tables', sa.Column('calculate_progress', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_etl_tables', 'calculate_progress')
    # ### end Alembic commands ###
