"""empty message

Revision ID: 88642b45beae
Revises: 3c663dc9e90b
Create Date: 2017-08-21 16:17:12.751000

"""

# revision identifiers, used by Alembic.
revision = '88642b45beae'
down_revision = '3c663dc9e90b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_adwords_google_drive_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bit_adwords_google_drive_storage')
    # ### end Alembic commands ###
