"""empty message

Revision ID: 897e232cda94
Revises: 5f1b9bb1cf7f
Create Date: 2017-08-28 16:43:25.995000

"""

# revision identifiers, used by Alembic.
revision = '897e232cda94'
down_revision = '5f1b9bb1cf7f'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_etl_tables', sa.Column('connector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bit_etl_tables', 'bit_connectors', ['connector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bit_etl_tables', type_='foreignkey')
    op.drop_column('bit_etl_tables', 'connector_id')
    # ### end Alembic commands ###
