"""empty message

Revision ID: 958e493ca62f
Revises: ef6f9bfeea60
Create Date: 2017-09-06 09:02:00.045000

"""

# revision identifiers, used by Alembic.
revision = '958e493ca62f'
down_revision = 'ef6f9bfeea60'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('tracking_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'tracking_url')
    # ### end Alembic commands ###
