"""empty message

Revision ID: 9a85e02050e0
Revises: 87d7cfb1f7c0
Create Date: 2017-12-12 14:26:15.553000

"""

# revision identifiers, used by Alembic.
revision = '9a85e02050e0'
down_revision = '87d7cfb1f7c0'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_etl_tables', sa.Column('downloaded_rows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_etl_tables', 'downloaded_rows')
    # ### end Alembic commands ###
