"""empty message

Revision ID: a1ab4ed966e0
Revises: 897e232cda94
Create Date: 2017-08-28 16:52:08.955000

"""

# revision identifiers, used by Alembic.
revision = 'a1ab4ed966e0'
down_revision = '897e232cda94'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_etl_tables', sa.Column('datasource', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_etl_tables', 'datasource')
    # ### end Alembic commands ###
