"""empty message

Revision ID: bcb3cf1fca20
Revises: f635ed1e0455
Create Date: 2017-08-23 15:13:50.770000

"""

# revision identifiers, used by Alembic.
revision = 'bcb3cf1fca20'
down_revision = 'f635ed1e0455'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_connectors_appsflyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=True),
    sa.Column('url_pat', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bit_connectors_appsflyer')
    # ### end Alembic commands ###
