"""empty message

Revision ID: c0d2834887cd
Revises: c10accd915ce
Create Date: 2017-08-14 14:27:21.082000

"""

# revision identifiers, used by Alembic.
revision = 'c0d2834887cd'
down_revision = 'c10accd915ce'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_facebook_daily_ad_insights', sa.Column('native_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_bit_facebook_daily_ad_insights_native_id'), 'bit_facebook_daily_ad_insights', ['native_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bit_facebook_daily_ad_insights_native_id'), table_name='bit_facebook_daily_ad_insights')
    op.drop_column('bit_facebook_daily_ad_insights', 'native_id')
    # ### end Alembic commands ###
