"""empty message

Revision ID: c90e78bc3ef9
Revises: 4ad33f99723a
Create Date: 2017-08-17 16:04:21.163000

"""

# revision identifiers, used by Alembic.
revision = 'c90e78bc3ef9'
down_revision = '4ad33f99723a'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_facebook_daily_ad_insights_impression_device', sa.Column('cost', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_facebook_daily_ad_insights_impression_device', 'cost')
    # ### end Alembic commands ###
