"""empty message

Revision ID: d104dafc402b
Revises: 79b791909dc3
Create Date: 2017-08-08 12:05:40.307000

"""

# revision identifiers, used by Alembic.
revision = 'd104dafc402b'
down_revision = '79b791909dc3'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_etl_tables', sa.Column('sync_periodic_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_etl_tables', 'sync_periodic_hour')
    # ### end Alembic commands ###
