"""empty message

Revision ID: d8897dfe0b16
Revises: a1ab4ed966e0
Create Date: 2017-08-29 11:25:38.854000

"""

# revision identifiers, used by Alembic.
revision = 'd8897dfe0b16'
down_revision = 'a1ab4ed966e0'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bit_chiter_connector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_chiter_connector',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('api_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url_pat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'bit_connectors.id'], name=u'bit_chiter_connector_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'bit_chiter_connector_pkey')
    )
    # ### end Alembic commands ###
