"""empty message

Revision ID: ecbe7bbcbd6c
Revises: fe6b80d74c39
Create Date: 2017-08-11 18:00:49.811000

"""

# revision identifiers, used by Alembic.
revision = 'ecbe7bbcbd6c'
down_revision = 'fe6b80d74c39'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_facebook_ad_campaigns', sa.Column('account_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_bit_facebook_ad_campaigns_account_id'), 'bit_facebook_ad_campaigns', ['account_id'], unique=True)
    op.add_column('bit_facebook_ad_sets', sa.Column('account_id', sa.String(length=255), nullable=True))
    op.add_column('bit_facebook_ad_sets', sa.Column('campaign_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_bit_facebook_ad_sets_account_id'), 'bit_facebook_ad_sets', ['account_id'], unique=True)
    op.create_index(op.f('ix_bit_facebook_ad_sets_campaign_id'), 'bit_facebook_ad_sets', ['campaign_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bit_facebook_ad_sets_campaign_id'), table_name='bit_facebook_ad_sets')
    op.drop_index(op.f('ix_bit_facebook_ad_sets_account_id'), table_name='bit_facebook_ad_sets')
    op.drop_column('bit_facebook_ad_sets', 'campaign_id')
    op.drop_column('bit_facebook_ad_sets', 'account_id')
    op.drop_index(op.f('ix_bit_facebook_ad_campaigns_account_id'), table_name='bit_facebook_ad_campaigns')
    op.drop_column('bit_facebook_ad_campaigns', 'account_id')
    # ### end Alembic commands ###
