"""empty message

Revision ID: ef6f9bfeea60
Revises: 7aacb302ef70
Create Date: 2017-08-29 13:09:40.910000

"""

# revision identifiers, used by Alembic.
revision = 'ef6f9bfeea60'
down_revision = '7aacb302ef70'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(u'bit_facebook_ad_account_connector_id_fkey',
                       'bit_facebook_ad_account', type_='foreignkey')
    op.drop_constraint(u'bit_facebook_connector_connector_id_fkey',
                       'bit_facebook_connector', type_='foreignkey')
    op.drop_column('bit_facebook_connector', 'connector_id')



    op.drop_constraint(u'bit_adwords_connector_connector_id_fkey',
                       'bit_adwords_connector', type_='foreignkey')
    op.drop_constraint(u'bit_adwords_google_drive_storage_connector_id_fkey',
                       'bit_adwords_google_drive_storage', type_='foreignkey')
    op.drop_column('bit_adwords_connector', 'connector_id')





    op.add_column('bit_facebook_connector',
                  sa.Column('id', sa.Integer(), nullable=False))

    op.add_column('bit_adwords_connector',
                  sa.Column('id', sa.Integer(), nullable=False))



    op.create_foreign_key(None, 'bit_adwords_connector', 'bit_connectors',
                          ['id'], ['id'])

    op.create_foreign_key(None, 'bit_adwords_google_drive_storage', 'bit_connectors',
                          ['connector_id'], ['id'])

    op.create_foreign_key(None, 'bit_facebook_connector', 'bit_connectors',
                          ['id'], ['id'])

    op.create_foreign_key(None, 'bit_facebook_ad_account',
                          'bit_connectors',
                          ['connector_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_facebook_connector', sa.Column('connector_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bit_facebook_connector', type_='foreignkey')
    op.create_foreign_key(u'bit_facebook_connector_connector_id_fkey', 'bit_facebook_connector', 'bit_connectors', ['connector_id'], ['id'])
    op.drop_column('bit_facebook_connector', 'id')
    op.drop_constraint(None, 'bit_facebook_ad_account', type_='foreignkey')
    op.create_foreign_key(u'bit_facebook_ad_account_connector_id_fkey', 'bit_facebook_ad_account', 'bit_facebook_connector', ['connector_id'], ['connector_id'])
    op.drop_constraint(None, 'bit_adwords_google_drive_storage', type_='foreignkey')
    op.create_foreign_key(u'bit_adwords_google_drive_storage_connector_id_fkey', 'bit_adwords_google_drive_storage', 'bit_adwords_connector', ['connector_id'], ['connector_id'])
    op.add_column('bit_adwords_connector', sa.Column('connector_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bit_adwords_connector', type_='foreignkey')
    op.create_foreign_key(u'bit_adwords_connector_connector_id_fkey', 'bit_adwords_connector', 'bit_connectors', ['connector_id'], ['id'])
    op.drop_column('bit_adwords_connector', 'id')
    # ### end Alembic commands ###
