"""empty message

Revision ID: f635ed1e0455
Revises: 79d8578108f1
Create Date: 2017-08-22 15:04:37.748000

"""

# revision identifiers, used by Alembic.
revision = 'f635ed1e0455'
down_revision = '79d8578108f1'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bit_adwords_campaign_performance_report', 'cost_per_mobile_app_purchases')
    op.drop_column('bit_adwords_campaign_performance_report', 'mobile_app_purchases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_adwords_campaign_performance_report', sa.Column('mobile_app_purchases', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bit_adwords_campaign_performance_report', sa.Column('cost_per_mobile_app_purchases', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
