"""empty message

Revision ID: fa6a90ecfed1
Revises: 9e8429737ba0
Create Date: 2017-08-13 19:17:28.119000

"""

# revision identifiers, used by Alembic.
revision = 'fa6a90ecfed1'
down_revision = '9e8429737ba0'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_facebook_daily_ad_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('buying_type', sa.String(length=255), nullable=True),
    sa.Column('unique_clicks', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['bit_facebook_ad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bit_facebook_daily_ad_insights')
    # ### end Alembic commands ###
