"""empty message

Revision ID: fe6b80d74c39
Revises: 46799507436e
Create Date: 2017-08-10 15:26:12.484000

"""

# revision identifiers, used by Alembic.
revision = 'fe6b80d74c39'
down_revision = '46799507436e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'bit_facebook_ad_campaigns_account_id_fkey', 'bit_facebook_ad_campaigns', type_='foreignkey')
    op.drop_column('bit_facebook_ad_campaigns', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_facebook_ad_campaigns', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'bit_facebook_ad_campaigns_account_id_fkey', 'bit_facebook_ad_campaigns', 'bit_facebook_ad_account', ['account_id'], ['id'])
    # ### end Alembic commands ###
