"""empty message

Revision ID: feb789fcbf9e
Revises: bcb3cf1fca20
Create Date: 2017-08-23 15:51:18.814000

"""

# revision identifiers, used by Alembic.
revision = 'feb789fcbf9e'
down_revision = 'bcb3cf1fca20'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_connectors_appsflyer', sa.Column('connector_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bit_connectors_appsflyer', 'bit_connectors', ['connector_id'], ['id'])
    op.drop_column('bit_connectors_appsflyer', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bit_connectors_appsflyer', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'bit_connectors_appsflyer', type_='foreignkey')
    op.drop_column('bit_connectors_appsflyer', 'connector_id')
    # ### end Alembic commands ###
